### ISSUE TITLE
[Feature Request] Adding Localizations from a local directory

### ISSUE THREAD

**Issue by takoyaro** [SCKorea/Shatagon#8]
I'm developing my own localizations for French and Japanese.
I'd like to test them by adding them to Shatagon from a local directory.

**Comment by Laeng** [comment]
Hi @takoyaro,
Thank you for using the Shatagon and requesting the feature! 😄
First of all, I want to tell you something.

This program is linked with the API of the Korean localization team's exclusive website.
If you develop patch through this program, I expect that you will experience inconvenience owing to our system. 😥

So I recommend two program.

https://github.com/h0useRus/StarCitizen
https://github.com/Shin0by/StarCitizen-Helper

Both programs have more advanced features than ours and can load files locally. 😀
While you check these, I'll talk about this request with @marona42!

Thank you.

**Comment by marona42** [comment]
Since we cannot ensure the contents of local directory's files, I did not take consider adding the local files.

If you want to test some your works, you'd better add your repository to the Shatagon temporarily by type some lines at 'Settings/LocalizationSettings.cs'. Unfortunately, I've not tested other repositories well, perhaps there are some errors on those feature. the issues about them are welcome xD

Otherwise you can PR to add Japanese/French repository/language to us or [Shin0by's StarCitizen-Helper](https://github.com/Shin0by/StarCitizen-Helper), the PR will be welcomed!
